### ISSUE TITLE
Cert admin email

### ISSUE THREAD

**Issue by jennryn** [creativecommons/certificates.creativecommons.org#21]
Hey @aldenstpage  and @pa-w , 

Right before he left, Rob set up the certificates@creativecommons.org email group, with me as the sole member and admin. 

I just tested it now, and 1) didn't receive the email test (below), and 2) it looks like I don't actually have admin access. Here's the group forum link he gave me: https://groups.google.com/a/creativecommons.org/forum/#!forum/certificates. When I click on that link I get a message that says "authorization failed."

Would you be able to help me either get access & add new members to the group, or set up a new group for this? I'm hoping to include the contact info in communication this week.  

Thank you very much!

Jennryn

**Comment by aldenstpage** [comment]
I looked into this already and forgot to close the ticket. The issue was resolved (Jennryn can feel free to reopen if I'm forgetting something)

**Comment by jennryn** [comment]
It was resolved. Thanks @aldenstpage !
