### ISSUE TITLE
# of CC licensed works

### ISSUE THREAD

**Issue by jennryn** [creativecommons/certificates.creativecommons.org#31]
@TimidRobot @kgodey  Is there a way to update the main creativecommons.org page with the updated # of CC licensed works? Currently it says 1.1 B and growing but our state of the commons report lists 1.4 B and growing. And the state of the commons is using 2017 data. 

 Also, what is the updated number? I'll need to update the CC Certificate materials with this.  Thanks!

**Comment by hugosolar** [comment]
The number was updated in the homepage widget (1.6 B). Should be ok now
