### ISSUE TITLE
Cert content options 

### ISSUE THREAD

**Issue by jennryn** [creativecommons/certificates.creativecommons.org#4]
@robmyers: 

For the Certificate we are hoping to have Cert content available 3 ways: 1) via downloadable OER on the Cert webpage (likely google docs and/or word docs, which I'll work on), 2) via text on Pressbooks, which students in the course can access (which I'll work on), and 3) via text--likely also Pressbooks, which students and non-students can freely access on our website, and which has the option for peer-review & annotation. For this option, we want to use Hypothesis: https://web.hypothes.is/. 

Here are directions to enable it on Pressbooks: https://wisc.pb.unizin.org/pressbooks101/chapter/annotation-with-hypothesis/. By June 15, can you set up the annotation option on ONLY the content option that we'd make public on certificates.creativecommons.org (but the content that is downloadable OER)?

**Comment by jennryn** [comment]
The text with Hypothesis annotations should ultimately be made public on a content page (we haven't built/published yet) on certificates.creativecommons.org.

**Comment by robmyers** [comment]
I've cloned the cert site and added hypothesis to that as suggested.
People can log in to comment on it using their WordPress.com login, so we don't need to worry about people signing up to the site to do that.

**Comment by robmyers** [comment]
We can export epub and PDF. Word is not supported. I believe that epub and PDF should be sufficient unless we are trying to integrate with any workflows that rely on Word.

**Comment by robmyers** [comment]
The epub and PDF links can be found in the book admin area on the "Exports" page.

**Comment by jennryn** [comment]
@robmyers per our chat last week the formatting is off in Hypothesis. Can you fix, please? 


Thank you.
